### ISSUE TITLE
Incorrect statement about linearity of networks with ReLU activations?

### ISSUE THREAD

**Issue by sporadicCactus** [amazon-research/network-deconvolution-pp#1]
Hi! There is a statement in your paper:
> In our toy problem, the output scales linearly with the input, (aX)w = a(Xw). This property actually generalizes to common networks with linear layers and ReLU-like activation functions;

Doesn't seem true to me. Common networks have biases in linear layers, and even with ReLU activations successfully model non-linear functions.

**Comment by yechengxi** [comment]
Right, we also considered this. We mentioned this as a detail in the appendix. 
The question is that if the bias term can introduce scale-invariance? Most likely not, because the bias term is completely external to the input. Especially if you imagine, if you multiply the input by 1e4, can some external bias terms resolve it? This bias terms will end up adding some offsets to your processed features, rather than scaling them.
